substitutions:
  name: fingerprint
  friendly_name: Fingerprint
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
packages:
  xio.radar:
    url: https://github.com/Xioshock/configs
    ref: main
    file: fingerprint/fingerprint.yaml
    refresh: 0s