substitutions:
  name: "device"
  friendly_name: "Device"
  project_name: "device"
  version: "1.0"
  board: esp32-c3-devkitm-1

esp32:
  board: $board
  framework:
    type: arduino

esphome:
  name: $name
  friendly_name: $friendly_name
  project:
    name: xio.$project_name
    version: $version

captive_portal:

api:
  
ota:

logger:
  #level: INFO  #You Can Use "INFO" Level
  baud_rate: 0

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  power_save_mode: none
  ap:
    ssid: "${friendly_name} AP"
    password: "${wifi_password}"
#  manual_ip:
#    static_ip: !secret ip_esp32mastbath
#    gateway: !secret ip_gateway
#    subnet: !secret ip_subnet
#    dns1: !secret ip_dns1

web_server:   #Avoid Using Web Server To Prevent Hang
  port: 80

binary_sensor:
  - platform: status
    name: "${friendly_name} Device Status"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s