substitutions:
  name: radar-hallway
  friendly_name: Radar Hallway
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
packages:
  xio.radar: github://Xioshock/configs/radar/radar.yaml
  refresh: 0s