substitutions:
  name: radar
  friendly_name: Radar
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
packages:
  xio.radar:
    url: https://github.com/Xioshock/configs
    ref: main
    file: radar/radar.yaml
    refresh: 0s
